dataset_path: ./DNDN/data/SocioPatternsDataset
model_path: ./DNDN/checkpoints
result_path: ./DNDN/results

use_wandb: True
log_name: dim01_layer5
log_WD: True
load_model: False
load_model_name: None

dataset: citation
dataset_size: small_graph
train_set_ratio: 0.8

epochs: 300
tolerance: 50
model_type: GAT
fusion: add
hidden_dim: 32
num_layers: 5
learning_rate: 0.001
weight_decay: 0.01
dropout: 0.1
batch_size: 10
test_epoch_interval: 1

save_train_result: True
save_test_result: True

seed: 1234
new_node_feat: True
use_edge_attn: True
save_model: True

p: 2  # p-wasserstein distance
kernel: wasserstein  # loss for PDs