result_dir: results
ckpt_dir: ckpt
logger_dir: logger
seed: 1234
repeat: 1
num_threads: 12
run_multiple_splits: []

data:
  name: citation
  dataset_size: small_graph
  batch_size: 10
  split: [0.8, 0.2]

train:
  gpus: [2]
  accelerator: gpu
  epochs: 300
  tolerance: 50
  monitor: train_loss
  pretrained_ckpt: null

optim:
  lr: 1e-3
  max_epoch: 1000
  weight_decay: 1e-2
  optimizer: adamw
  lr_scheduler: True
  scheduler: step
  steps: 100

model:
  model_type: GAT
  fusion: add
  hidden_dim: 32
  num_layers: 5
  dropout: 0.1
  new_node_feat: True
  use_edge_attn: True
  p: 2  # p-wasserstein distance
  kernel: wasserstein  # loss for PDs
  loss_type: dim0


